### PR TITLE
Added type declarations

### PR DESCRIPTION
**Pull request by w8r**
Hi @robertknight , thank you for the wonderful library. This PR just exposes the typescript types

### CODE REVIEW

**Comment by robertknight** [comment]
Hello, thank you for the PR and sorry for the delay. This looks good to me.

**Comment by robertknight** [comment]
Published as v0.7.0. Sorry for the long wait!

**Comment by basil** [comment]
Were these types ever published correctly? They don't appear to be present in the tarball at https://registry.npmjs.org/tex-linebreak/-/tex-linebreak-0.7.0.tgz and I still can't use this library from my TypeScript project. As a workaround, I ran the commands from this PR to manually generate the types and placed them in my project in a `tex-linebreak.d.ts` file.

**Comment by robertknight** [comment]
You're correct, the types are missing from the `files` globs in package.json - https://github.com/robertknight/tex-linebreak/blob/1712a4018cd076ac223ebb561e7bec3c64aae51b/package.json#L34. Sorry about that.

**Comment by robertknight** [comment]
I have published v0.7.1 which includes the types. Please give it a try.

**Comment by basil** [comment]
Thank you, this worked.

**Pull request merged**
